Add match-all addShMock invocation
The existing configuration for a match-everything sh mock uses `null` as the argument, which causes this error:

```console
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method com.lesfurets.jenkins.unit.PipelineTestHelper#addShMock.
Cannot resolve which method to invoke for [null, class TestIsDatabricksRepo$_testNoDbxFolder_closure5] due to overlapping prototypes between:
	[class java.lang.String, class groovy.lang.Closure]
	[class java.util.regex.Pattern, class groovy.lang.Closure]
```

This adds a new method signature (no args) to match everything, instead.